import Layout from "@/components/layout"
import Head from "next/head"
import Image from "next/image"


export default function about() {


  return (
    <Layout>
        <Head>
            <title>Zengi Mimarlık | Hakkımızda</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500&display=swap" rel="stylesheet"/>
        </Head>

        <section className="py-20 about-page sm:py-32 ">
        <div className="container px-5 py-10 mx-auto sm:px-10 bg-center bg-no-repeat h-5/6 bg-[url('/images/bg_lg_op.png')]">
                <div className="grid items-center grid-cols-12 lg:gap-12">
                    <div className="col-span-12 about-item-description lg:col-span-8 ">
                        <h2 className="w-2/3 pb-2 mb-3 text-xl font-semibold tracking-wider uppercase border-b-2 border-b-gray-200">zengi mimarlık</h2>
                            <p className="text-justify">
                            SLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                            </p>
                            <p className="text-justify">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                            </p>
                    </div>
                    <div className="col-span-12 about-item-description lg:col-span-4">
                        <Image src="/images/22.jpg" width={400} height={400} alt="About Image" className="hidden ml-auto lg:block"></Image>
                    </div>
                </div>
                <div className="w-full py-4 about-item-description">
                    <h1 className="pb-2 mb-3 text-xl font-semibold tracking-wider uppercase border-b-2 border-gray-200 lg:w-1/3">zengi mimarlık  <span className="lg:block">olarak neler yapıyoruz?</span> </h1>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
                   <div className="w-full py-4 about-item-description">
                    <h1 className="pb-2 mb-3 text-xl font-semibold tracking-wider uppercase border-b-2 border-gray-200 lg:w-1/3">zengi ailesi </h1>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
                   <div className="w-full about-item-description">
                    <h1 className="pb-2 mb-3 text-xl font-semibold tracking-wider uppercase border-b-2 border-gray-200 lg:w-1/3">zengi mimarisi </h1>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
            </div>
        </section>

    </Layout>
  )
}
