import Layout from "@/components/layout"
import Head from "next/head"
import Image from "next/image"

export default function about() {
  return (
    <Layout>
        <Head>
            <title>Zengi Mimarlık | Hakkımızda</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="about-page py-20 sm:py-32">
            <div className="container mx-auto py-10 px-5 sm:px-10">
                <div className="grid grid-cols-12 items-center lg:gap-12">
                    <div className="about-item-description col-span-12 lg:col-span-8 ">
                        <h2 className="mb-3 font-semibold text-xl pb-2 border-b-2 border-b-gray-200 uppercase w-2/3 tracking-wider">zengi mimarlık</h2>
                            <p className="text-justify">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                            </p>
                            <p className="text-justify">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                            </p>
                    </div>
                    <div className="about-item-description col-span-12 lg:col-span-4">
                        <Image src="/images/22.jpg" width={400} height={400} alt="About Image" className="ml-auto hidden lg:block"></Image>
                    </div>
                </div>
                <div className="about-item-description w-full py-4">
                    <h1 className="mb-3 font-semibold text-xl pb-2 border-b-2 border-gray-200 uppercase tracking-wider lg:w-1/3">zengi mimarlık  <span className="lg:block">olarak neler yapıyoruz?</span> </h1>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
                   <div className="about-item-description w-full py-4">
                    <h1 className="mb-3 font-semibold text-xl pb-2 border-b-2 border-gray-200 uppercase tracking-wider lg:w-1/3">zengi ailesi </h1>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
                   <div className="about-item-description w-full">
                    <h1 className="mb-3 font-semibold text-xl pb-2 border-b-2 border-gray-200 uppercase tracking-wider lg:w-1/3">zengi mimarisi </h1>
                        <p className="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
            </div>
        </section>

    </Layout>
  )
}
