import Layout from '../components/layout'
import Head from 'next/head'
import { Input, Textarea, Grid } from '@nextui-org/react'
import Link from 'next/link'

export default function Contact() {
  return (
    <Layout>
        <Head>
          <title>Zengi Mimarlık | Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className='contact-page px-5 lg:px-0 py-32 lg:py-40'>
        <Grid.Container gap={2} justify="center" className="lg:px-20 z-10">
            <Grid xs={12} md={4}>
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.521260322283!2d106.8195613507864!3d-6.194741395493371!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f5390917b759%3A0x6b45e67356080477!2sPT%20Kulkul%20Teknologi%20Internasional!5e0!3m2!1sen!2sid!4v1601138221085!5m2!1sen!2sid"
              width="100%"
              height="450"
              frameBorder="0"
              style={{ border: 0 }}
              allowFullScreen=""
              aria-hidden="false"
              tabIndex="0"
            />
            </Grid>
            <Grid xs={12} md={8} className='bg-gray-100 items-start py-10 lg:px-20 flex flex-col'>
              <form className='contact-form w-full z-10 relative'>
                <Grid.Container gap={2}>
                  <Grid xs={6}>
                    <Input 
                      type={'text'}
                      fullWidth={true}
                      clearable
                      underlined 
                      labelPlaceholder="Adınız ve Soyadınız" 
                      color="default" />
                  </Grid>
                  <Grid xs={6}>
                    <Input 
                      type={'tel'}
                      fullWidth={true}
                      clearable
                      underlined 
                      labelPlaceholder="Telefon Numaranız" 
                      color="default" />
                  </Grid>
                  <Grid xs={12} className='my-4'>
                  <Textarea
                      fullWidth={true}
                      clearable
                      underlined
                      color="default"
                      labelPlaceholder="Underlined Textarea"
                    />
                  </Grid>
                  <Grid xs={6}>
                  <Input 
                      type={'submit'}
                      fullWidth={true}
                      underlined 
                      value={'Gönder'}
                      color="default" />
                  </Grid>
                  <Grid xs={6}>
                  <Input 
                      type={'reset'}
                      fullWidth={true}
                      underlined 
                      value={'Temizle'}
                      color="default" />
                  </Grid>
                </Grid.Container>
              </form>
              <ul className='nav flex flex-col text-gray-500 pt-10'>
                <li className='text-sm'><span className='uppercase font-medium'>telefon:</span> <Link href='tel:902169998853'>+90 (216) 999 88 53</Link></li>
                <li className='text-sm'><span className='uppercase font-medium'>e-mail:</span> <Link href='tel:902169998853'>info@zengimimarlik.com</Link></li>
                <li className='text-sm'><span className='text-gray-500 font-medium uppercase'>adres:</span> <Link href='tel:902169998853'>Tantavi Mh. Estergon Cd. <br/> No24F/285 P.K 34764 Ümraniye/İstanbul </Link></li>
              </ul>
            </Grid>

        </Grid.Container>
        </section>
    </Layout>
  )
}
