import Layout from '../components/layout'
import Head from 'next/head'
import { Input, Textarea, Grid } from '@nextui-org/react'
import Link from 'next/link'

export default function Contact() {
  return (
    <Layout>
        <Head>
          <title>Zengi Mimarlık | Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500&display=swap" rel="stylesheet"/>
        </Head>
        <section className='px-5 py-32 contact-page lg:px-0 lg:py-40'>
        <Grid.Container gap={2} justify="center" className="z-10 p-0 lg:px-20">
            <Grid xs={12} md={4} className='py-0 pr-4'>
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.521260322283!2d106.8195613507864!3d-6.194741395493371!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f5390917b759%3A0x6b45e67356080477!2sPT%20Kulkul%20Teknologi%20Internasional!5e0!3m2!1sen!2sid!4v1601138221085!5m2!1sen!2sid"
              width="100%"
              height="100%"
              frameBorder="0"
              style={{ border: 0 }}
              allowFullScreen=""
              aria-hidden="false"
              tabIndex="0"
              className='mb-10 lg:h-full h-96'
            />
            </Grid>
            <Grid xs={12} md={8} className='flex flex-col items-start py-10 bg-gray-100 lg:px-20'>
              <form className='relative z-10 w-full contact-form'>
                <Grid.Container gap={2}>
                  <Grid xs={6}>
                    <Input 
                      type={'text'}
                      fullWidth={true}
                      clearable
                      underlined 
                      labelPlaceholder="Adınız ve Soyadınız" 
                      color="default" />
                  </Grid>
                  <Grid xs={6}>
                    <Input 
                      type={'tel'}
                      fullWidth={true}
                      clearable
                      underlined 
                      labelPlaceholder="Telefon Numaranız" 
                      color="default" />
                  </Grid>
                  <Grid xs={12} className='my-4 ' >
                  <Textarea
                      fullWidth={true}
                      clearable
                      underlined
                      color="default"
                      labelPlaceholder=" Underlined Textarea"
                      style={{
                        backgroundColor:"rgb(217,217,217)", margin:"0"
                      }}
                    />
                  </Grid>
                  <Grid xs={6}>
                  <Input 
                      type={'submit'}
                      fullWidth={true}
                      underlined 
                      value={'Gönder'}
                      color="default" />
                  </Grid>
                  <Grid xs={6}>
                  <Input 
                      type={'reset'}
                      fullWidth={true}
                      underlined 
                      value={'Temizle'}
                      color="default" />
                  </Grid>
                </Grid.Container>
              </form>
              <ul className='flex flex-col pt-10 text-gray-500 nav'>
                <li className='text-sm'><span className='font-medium uppercase'>telefon:</span> <Link href='tel:902169998853'>+90 (216) 999 88 53</Link></li>
                <li className='text-sm'><span className='font-medium uppercase'>e-mail:</span> <Link href='tel:902169998853'>info@zengimimarlik.com</Link></li>
                <li className='text-sm'><span className='font-medium text-gray-500 uppercase'>adres:</span> <Link href='tel:902169998853'>Tantavi Mh. Estergon Cd. <br/> No24F/285 P.K 34764 Ümraniye/İstanbul </Link></li>
              </ul>
              <div className='flex justify-center w-full pt-4'>
              
              <Link href="/">
              <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 16 16" height="1.5em" width="1.4em" xmlns="http://www.w3.org/2000/svg"><path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path></svg>
              </Link>
              <Link href="/"><svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg"><path d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm215.3 337.7c.3 4.7.3 9.6.3 14.4 0 146.8-111.8 315.9-316.1 315.9-63 0-121.4-18.3-170.6-49.8 9 1 17.6 1.4 26.8 1.4 52 0 99.8-17.6 137.9-47.4-48.8-1-89.8-33-103.8-77 17.1 2.5 32.5 2.5 50.1-2a111 111 0 0 1-88.9-109v-1.4c14.7 8.3 32 13.4 50.1 14.1a111.13 111.13 0 0 1-49.5-92.4c0-20.7 5.4-39.6 15.1-56a315.28 315.28 0 0 0 229 116.1C492 353.1 548.4 292 616.2 292c32 0 60.8 13.4 81.1 35 25.1-4.7 49.1-14.1 70.5-26.7-8.3 25.7-25.7 47.4-48.8 61.1 22.4-2.4 44-8.6 64-17.3-15.1 22.2-34 41.9-55.7 57.6z"></path></svg>
              </Link>
              <Link href="/"><svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg"><path d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm167 633.6C638.4 735 583 757 516.9 757c-95.7 0-178.5-54.9-218.8-134.9C281.5 589 272 551.6 272 512s9.5-77 26.1-110.1c40.3-80.1 123.1-135 218.8-135 66 0 121.4 24.3 163.9 63.8L610.6 401c-25.4-24.3-57.7-36.6-93.6-36.6-63.8 0-117.8 43.1-137.1 101-4.9 14.7-7.7 30.4-7.7 46.6s2.8 31.9 7.7 46.6c19.3 57.9 73.3 101 137 101 33 0 61-8.7 82.9-23.4 26-17.4 43.2-43.3 48.9-74H516.9v-94.8h230.7c2.9 16.1 4.4 32.8 4.4 50.1 0 74.7-26.7 137.4-73 180.1z"></path></svg>
              </Link>
              <Link href="https://www.instagram.com/zengimimarlik/"><svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg"><path d="M512 378.7c-73.4 0-133.3 59.9-133.3 133.3S438.6 645.3 512 645.3 645.3 585.4 645.3 512 585.4 378.7 512 378.7zM911.8 512c0-55.2.5-109.9-2.6-165-3.1-64-17.7-120.8-64.5-167.6-46.9-46.9-103.6-61.4-167.6-64.5-55.2-3.1-109.9-2.6-165-2.6-55.2 0-109.9-.5-165 2.6-64 3.1-120.8 17.7-167.6 64.5C132.6 226.3 118.1 283 115 347c-3.1 55.2-2.6 109.9-2.6 165s-.5 109.9 2.6 165c3.1 64 17.7 120.8 64.5 167.6 46.9 46.9 103.6 61.4 167.6 64.5 55.2 3.1 109.9 2.6 165 2.6 55.2 0 109.9.5 165-2.6 64-3.1 120.8-17.7 167.6-64.5 46.9-46.9 61.4-103.6 64.5-167.6 3.2-55.1 2.6-109.8 2.6-165zM512 717.1c-113.5 0-205.1-91.6-205.1-205.1S398.5 306.9 512 306.9 717.1 398.5 717.1 512 625.5 717.1 512 717.1zm213.5-370.7c-26.5 0-47.9-21.4-47.9-47.9s21.4-47.9 47.9-47.9 47.9 21.4 47.9 47.9a47.84 47.84 0 0 1-47.9 47.9z"></path></svg>
              </Link>
              </div>
              
            </Grid>

        </Grid.Container>
        </section>
    </Layout>
  )
}
