import Head from 'next/head'
import Layout from '../components/layout'
import Hero from '../components/home/hero'
import Project from '../components/home/project'

export default function Home() {
  return (
    <Layout>
        <Head>
          <title>Zengi Mimarlık | Anasayfa</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <Hero/>
          <Project/>
    </Layout>
  )
}


