import Layout from "@/components/layout"
import Head from "next/head"
import Slider2 from "@/components/slider2"
import Project from "@/components/project/gallery"
import GalleryHome from "@/components/home/galleryHome"


export default function project() {

  const slides = [
    {
      id: 1,
      title: "RIVA VILLA PROJESİ",
      image: "/images/detail.jpg",
    },
    // {
    //   id: 2,
    //   title: "RIVA VILLA PROJESİ2",
    //   image: "/images/2.jpg",
    // },
    // {
    //   id: 3,
    //   title: "RIVA VILLA PROJESİ3",
    //   image: "/images/3.jpg",
    // },
    // {
    //   id: 4,
    //   title: "RIVA VILLA PROJESİ4",
    //   image: "/images/4.jpg",
    // },
  ];

  return (
    <Layout>
        <Head>
            <title>Zengi Mimarlık | Proje</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500&display=swap" rel="stylesheet"/>
        </Head>
        <Slider2 slides={slides}  />
        <GalleryHome/>  


    </Layout>
  )
}
